upstream backend_round_robin {
    server 127.0.0.1:5001 max_fails=1 fail_timeout=5s;
    server 127.0.0.1:5002 max_fails=1 fail_timeout=5s;
}

upstream backend_least_conn {
    least_conn;

    server 127.0.0.1:5001 max_fails=1 fail_timeout=5s;
    server 127.0.0.1:5002 max_fails=1 fail_timeout=5s;
}

upstream backend_ip_hash {
    ip_hash;

    server 127.0.0.1:5001 max_fails=1 fail_timeout=5s;
    server 127.0.0.1:5002 max_fails=1 fail_timeout=5s;
}

server {
    listen 8000;

    location / {
        proxy_pass http://backend_round_robin;

        proxy_connect_timeout 1s;
        proxy_read_timeout 5s;

        proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
        proxy_next_upstream_tries 2;
    }
}