# ==============================
# ROUND ROBIN
# ==============================

# Distribuye las peticiones alternadamente
# entre los dos backends.
upstream backend_round_robin {

    server 127.0.0.1:5001 max_fails=1 fail_timeout=5s;
    server 127.0.0.1:5002 max_fails=1 fail_timeout=5s;
}


# ==============================
# LEAST CONNECTIONS
# ==============================

upstream backend_least_conn {

    # Envía la petición al backend
    # con menos conexiones activas.
    least_conn;

    server 127.0.0.1:5001 max_fails=1 fail_timeout=5s;
    server 127.0.0.1:5002 max_fails=1 fail_timeout=5s;
}


# ==============================
# IP HASH
# ==============================

upstream backend_ip_hash {

    # Un mismo cliente tiende a ser
    # enviado siempre al mismo backend.
    ip_hash;

    server 127.0.0.1:5001 max_fails=1 fail_timeout=5s;
    server 127.0.0.1:5002 max_fails=1 fail_timeout=5s;
}


# ==============================
# SERVIDOR NGINX
# ==============================

server {

    # Nginx escucha en el puerto 8000.
    listen 8000;

    location / {

        # Algoritmo actualmente activo.
        proxy_pass http://backend_round_robin;

        # Tiempo máximo para conectar con un backend.
        proxy_connect_timeout 1s;

        # Tiempo máximo de espera por respuesta.
        proxy_read_timeout 5s;

        # Si un backend falla, intenta con otro.
        proxy_next_upstream error timeout http_500 http_502 http_503 http_504;

        # Máximo de intentos entre los backends.
        proxy_next_upstream_tries 2;
    }
}
